version: '2'
services:
  api:
    container_name: fenv_api
    build: .
    restart: always
    working_dir: /src
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./:/src
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--debug", "--reload-dir", "."]
  db:
    image: mongo:latest
    container_name: fenv_api_db
    restart: always
    environment: 
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_USERNAME=${MONGODB_USERNAME}
      - MONGO_PASSWORD=${MONGODB_PASSWORD}
    ports: 
      - "27017:27017"
    volumes: 
      - ./config/init_database.sh:/docker-entrypoint-initdb.d/init_database.sh
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config: